# Site Settings
title: CV Josep Anton Mir Tutusaus
url: 'https://jantonz.github.io/Resume/'
#baseurl: '/online-cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Josep Anton Mir Tutusaus
tagline: Environmental Engineer, Data Scientist, Python & R developer, Deep Learning Ninja
pic: profile0.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Ph.D. in Environmental Science and Technology by training, although soon
          I found myself concentrating on developing Machine Learning and Deep Learning
          models. Lately, my focus is on exploring the application of Artificial
          Intelligence to Environmental Sciences.'

#sidebar links
email: jantonz@gmail.com
#phone: 012 345 6789
website: researchgate.net/profile/Josep_Anton_Mir_Tutusaus #do not add http://
linkedin: josepantonmir
github: jantonz
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
